### ISSUE TITLE
Issue with all Links on this url https://pionia.netlify.app/moonlight/moonlight-architecture/

### ISSUE THREAD

**Issue by isaacssemugenyi** [PioniaPHP-project/pionia-docs#3]
All the links on that page are pointing to localhost:1313 including those on the side bar

**Comment by jet2018** [comment]
This is usually because your app has cached the site. Let try to look into this. But in the meantime, try to delete your caches and try again.

**Comment by jet2018** [comment]
This issue should resolved now
